# This is a config for E2B sandbox template.
# You can use template ID (9psru9upclsabllo03yv) or template name (cyclotruc__gitingest) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("cyclotruc__gitingest") # Sync sandbox
# sandbox = await AsyncSandbox.create("cyclotruc__gitingest") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cyclotruc__gitingest')

team_id = "6154833f-d6de-4abb-929b-c580b082ebf9"
dockerfile = "e2b.Dockerfile"
template_name = "cyclotruc__gitingest"
template_id = "9psru9upclsabllo03yv"
